[author]
name = "example"
email = "example@local"

[challenge.metadata]
name = "compose-type"
flag = "CTF{sample_flag}"

type = "web"
points = 200

[challenge.env]
docker_compose = "docker-compose.yml"
default_port_var = "APP_PORT"
web_root = "challenge"
