[author]
name = "fristonio"
email = "contact+fristonio@sdslabs.co.in"
ssh_key = "ssh-rsa AAAAB3NzaC1y"

[challenge.metadata]
name = "docker-type"
flag = "FLAG{r3GEx_i5_3vi1!!}"
type = "bare"
points = 200

[[challenge.metadata.hints]]
text = "simple_hint_1"
points = 10

[[challenge.metadata.hints]]
text = "simple_hint_2"
points = 20

[challenge.env]
docker_context = "docker-file"
ports = [10005]
