[author]
name = "fristonio"
email = "contact+fristonio@sdslabs.co.in"

[challenge.metadata]
name = "docker-type"
flag = "FLAG{r3GEx_i5_3vi1!!}"
type = "bare"
points = 200

[[challenge.metadata.hints]]
text = "simple_hint_1"
points = 10

[[challenge.metadata.hints]]
text = "simple_hint_2"
points = 20

[challenge.env]
docker_context = "docker-file"
ports = [10005]
default_port = 10005

[resource]
cpu_shares = 512
memory_limit = 536870912
pids_limit = 100
cpuslimit = 0.25
