trigger:
- main
- master

pr:
- main
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.23.0'
- script: |
    make check_format
    go vet ./...
    go test -race ./...
  displayName: 'Validate and test'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    make build
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Build Beast'
