trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin'
  GOROOT: '/usr/local/go1.11'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    sudo apt update
    sudo apt install docker-ce docker-ce-cli containerd.io docker.io
    sudo usermod -a -G docker $USER
  displayName: 'Set up the Go and Docker workspace'

- script: |
    mkdir ~/.beast
    touch ~/.beast/config.toml
    touch ~/.beast/secret.key
    touch ~/.beast/authorized_keys
    touch ~/.beast/staging
    touch ~/.beast/remote
    touch ~/.beast/scripts
    echo -e "available_sidecars = [\"mysql\"]" >> ~/.beast/config.toml
    echo -e "jwt_secret = \"beast\"" >> ~/.beast/config.toml
    echo -e "allowed_base_images = [\"ubuntu:16.04\", \"php:7.1-cli\"]" >> ~/.beast/config.toml
    echo -e "authorized_keys_file = /home/$USER/.beast/authorized_keys" >> ~/.beast/config.toml
    echo -e "[remote]" >> ~/.beast/config.toml
    echo -e "ssh_key = \"/home/$USER/.beast/secret.key\"" >> ~/.beast/config.toml
    echo -e "url = \"git@github.com:sdslabs/nonexistent.git\"" >> ~/.beast/config.toml
    echo -e "name = \"nonexistent\"" >> ~/.beast/config.toml
    echo -e "branch = \"nonexistent\"" >> ~/.beast/config.toml
  workingDirectory: '$(modulePath)'
  displayName: 'Setup Beast Global Directory'

- script: |
    make build
  workingDirectory: '$(modulePath)'
  displayName: 'Build Beast'

# - script: |
#     make requirements
#   workingDirectory: '$(modulePath)'
#   displayName: 'Build Requirements'

- script: |
    make test
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests'
