trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- script: |
    sudo apt update
    sudo apt install docker.io
    sudo usermod -a -G docker $USER
    sudo systemctl unmask docker
    sudo systemctl start docker
  displayName: 'Set up the Docker workspace'

- script: |
    mkdir ~/.beast
    cp _examples/example.config.toml ~/.beast/config.toml
    touch ~/.beast/secret.key
    touch ~/.beast/authorized_keys
    mkdir ~/.beast/staging
    mkdir ~/.beast/remote
    mkdir ~/.beast/scripts
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Setup Beast Global Directory'

- script: |
    make build
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Build Beast'

- script: |
    make requirements
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Build Requirements'

- script: |
    echo -ne "ssh-rsa AAAAB3NzaC1y" > pub.key
    beast create-author --name fristonio --email contact+fristonio@sdslabs.co.in --publickey pub.key -v --username fristonio --password pass123
    make test
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Run tests'
