trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin'
  GOROOT: '/usr/local/go1.11'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    sudo apt update
    sudo apt install docker-ce
    sudo apt install docker.io
    sudo usermod -a -G docker $USER
  displayName: 'Set up the Go and Docker workspace'

- script: |
    make build
  workingDirectory: '$(modulePath)'
  displayName: 'Build Beast'

- script: |
    make requirements
  workingDirectory: '$(modulePath)'
  displayName: 'Build Requirements'

- script: |
    make test
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests'
