site_name: Beast

nav:
  - Home: README.md
  - Setup: Setup.md
  - Getting started: GettingStarted.md
  - Usage: Usage.md
  - Authentication: APIAuth.md
  - Challenges:
      - Configuration: ChallConfig.md
      - Types: ChallTypes.md
      - Samples: SampleChallenges.md
  - Architecture: Architecture.md
  - Features: Features.md
  - Deployment: Deployment.md
  - Contributing: Contribution.md
  - Command reference: cmdref/beast.md

theme: mkdocs
