[author]
name = "fristonio"
email = "contact+fristonio@sdslabs.co.in"
ssh_key = "ssh-rsa AAAAB3NzaC1y"

[challenge.metadata]
name = "static-chall"
flag = "BACKDOOR{SAMPLE_FLAG}"
type = "static"
hints = ["static_hint_1", "static_hint_2"]
maxPoints = 100
minPoints = 50
tags = ["easy", "web"]
