package database

import (
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/araddon/dateparse"

	"github.com/sdslabs/beastv4/core"
	"github.com/sdslabs/beastv4/core/config"
	log "github.com/sirupsen/logrus"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// The `challenges` table has the following columns
// name
// author
// format
// container_id
// image_id
// status
//
// Some hooks needs to be attached to these database transaction, and on the basis of
// the type of the transaction that is performed on the challenge table, we need to
// perform some action.
//
// Use gorm hooks for these purpose, currently the following hooks are
// implemented.
// * AfterUpdate
// * AfterCreate
// * AfterSave
// * AfterDelete
//
// All these hooks are used for generating the access shell script for the challenge
// to the challenge author
type Challenge struct {
	gorm.Model

	Name               string `gorm:"not null;type:varchar(64);unique"`
	DynamicFlag        bool   `gorm:"not null;default:false"`
	Flag               string `gorm:"type:text"`
	Type               string `gorm:"type:varchar(64)"`
	Difficulty         string `gorm:"not null;default:'medium'"`
	MaxAttemptLimit    int    `gorm:"default:-1"`
	PreReqs            string `gorm:"type:text"`
	Assets             string `gorm:"type:text"`
	AdditionalLinks    string `gorm:"type:text"`
	Description        string `gorm:"type:text"`
	Format             string `gorm:"not null"`
	ContainerId        string `gorm:"size:64;unique"`
	ImageId            string `gorm:"size:64;unique"`
	Status             string `gorm:"not null;default:'Undeployed'"`
	DeploymentType     string `gorm:"not null;default:'standard_docker'"`
	AuthorID           uint   `gorm:"not null"`
	HealthCheck        uint   `gorm:"not null;default:1"`
	Points             uint   `gorm:"default:0"`
	MaxPoints          uint   `gorm:"default:0"`
	MinPoints          uint   `gorm:"default:0"`
	Ports              []Port
	Tags               []*Tag  `gorm:"many2many:tag_challenges;constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	Users              []*User `gorm:"many2many:user_challenges;"`
	ServerDeployed     string  `gorm:"type:varchar(64)"`
	Instanced          bool    `gorm:"not null;default:false"`
	InstanceExpiration int64   `gorm:"default:0"`
}

type UserChallenges struct {
	ID        uint `gorm:"primaryKey"`
	CreatedAt time.Time
	User      User `gorm:"foreignKey:UserID"`
	UserID    uint

	Challenge   Challenge `gorm:"foreignKey:ChallengeID"`
	ChallengeID uint
	Tries       uint   `gorm:"not null;default:0"`
	Solved      bool   `gorm:"not null;default:false;index"`
	Flag        string `gorm:"type:text"`
	Cheating    bool   `gorm:"not null;default:false"`
}

type ChallengeAttempt struct {
	Id          uint      `json:"id"`
	UserId      uint      `json:"userId"`
	ChallengeID uint      `json:"challengeId"`
	Username    string    `json:"username"`
	SolvedAt    time.Time `json:"solvedAt"`
	Flag        string    `json:"flag"`
	Correct     bool      `json:"correct"`
	Cheating    bool      `json:"cheating"`
}
type UserLeaderboardResp struct {
	Id             uint         `json:"id" example:"5"`
	Username       string       `json:"username" example:"ABCD"`
	Score          uint         `json:"score" example:"750"`
	Rank           int64        `json:"rank" example:"15"`
	TimeSeriesdata []TimeSeries `json:"timeSeriesData"`
}
type TimeSeries struct {
	Timestamp time.Time `json:"timestamp" example:"2018-12-31T22:20:08"`
	Score     uint      `json:"score" example:"750"`
}

type TimeAggBucket int

const (
	LessThan10Min TimeAggBucket = iota
	Between10And100Min
	Between100MinAnd12Hr
	Between12HrAnd24Hr
	Between1DayAnd1Month
	Between1MonthAnd1Year
	MoreThan1Year
)

// The `DynamicFlags` table has the following columns
// name
// flag
// It stores all the flags dynamically generated by the challenge containers
// Thus, for same challenge, there can be multiple flags
type DynamicFlag struct {
	gorm.Model

	Name string `gorm:"not null;type:varchar(64)"`
	Flag string `gorm:"type:text;unique"`
}

// Create an entry for the challenge in the Challenge table
// It returns an error if anything wrong happen during the
// transaction.
func CreateChallengeEntry(challenge *Challenge) error {

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Begin()

	if tx.Error != nil {
		return fmt.Errorf("error while starting transaction %w", tx.Error)
	}

	if err := tx.FirstOrCreate(challenge, *challenge).Error; err != nil {
		tx.Rollback()
		return err
	}

	return tx.Commit().Error
}

// Query challenges table to get all the entries in the table
func QueryAllChallenges() ([]Challenge, error) {
	var challenges []Challenge

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Preload("Ports").Preload("Tags").Find(&challenges)

	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return nil, nil
	}

	return challenges, tx.Error
}

func QueryAllChallengesMetadata() ([]Challenge, error) {
	var challenges []Challenge

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Select("id", "name", "created_at", "points", "difficulty", "instanced", "instance_expiration", "status").
		Preload("Tags").
		Find(&challenges)

	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return nil, nil
	}

	return challenges, tx.Error
}

// Queries all the challenges entries where the column represented by key
// have the value in value.
func QueryChallengeEntries(key string, value string) ([]Challenge, error) {
	queryKey := fmt.Sprintf("%s = ?", key)

	var challenges []Challenge

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Preload("Tags").Preload("Ports").Where(queryKey, value).Find(&challenges)
	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return nil, nil
	}

	if tx.Error != nil {
		return challenges, tx.Error
	}

	return challenges, nil
}

// QueryChallengeEntriesMetadata returns only selected columns: Name, ID, Tags, CreatedAt, Points, Difficulty, Instanced, InstanceExpiration, Status
func QueryChallengeEntriesMetadata(key string, value string) ([]Challenge, error) {
	queryKey := fmt.Sprintf("%s = ?", key)

	var challenges []Challenge

	DBMux.Lock()
	defer DBMux.Unlock()

	// Only select the required columns, but preload Tags for tag names
	tx := Db.Select("id", "name", "created_at", "points", "difficulty", "instanced", "instance_expiration", "status").
		Preload("Tags").
		Where(queryKey, value).
		Find(&challenges)

	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return nil, nil
	}

	if tx.Error != nil {
		return challenges, tx.Error
	}

	return challenges, nil
}

// Queries all the challenges entries where the column matches
func QueryChallengeEntriesMap(whereMap map[string]interface{}) ([]Challenge, error) {

	var challenges []Challenge

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Where(whereMap).Find(&challenges)
	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return nil, nil
	}

	if tx.Error != nil {
		return challenges, tx.Error
	}

	return challenges, nil
}

// Using the column value in key and value in value get the first
// result of the query.
func QueryFirstChallengeEntry(key string, value string) (Challenge, error) {
	challenges, err := QueryChallengeEntries(key, value)
	if err != nil {
		return Challenge{}, err
	}

	if len(challenges) == 0 {
		return Challenge{}, nil
	}

	return challenges[0], nil
}

// Check Pre Reqs Status
func CheckPreReqsStatus(challenge Challenge, userID uint) (bool, error) {
	// Split the PreReqs field to get the list of prerequisite challenge names
	preReqChallengeNames := strings.Split(challenge.PreReqs, core.DELIMITER)

	// Check if all prerequisite challenges are solved
	for _, preReq := range preReqChallengeNames {
		var preReqChallenge Challenge
		err := Db.Where("name = ?", preReq).First(&preReqChallenge).Error
		if err != nil {
			return false, err
		}

		var userChallenge UserChallenges
		err = Db.Where("user_id = ? AND challenge_id = ? AND solved = ?", userID, preReqChallenge.ID, true).First(&userChallenge).Error
		if err != nil {
			if err == gorm.ErrRecordNotFound {
				return false, nil
			}
			return false, err
		}
	}

	return true, nil
}

// Get User Related Challenges
func GetUserPreviousTries(userID uint, challengeID uint) (int, error) {
	var userChallenges UserChallenges
	err := Db.Where("user_id = ? AND challenge_id = ?", userID, challengeID).First(&userChallenges).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			// Return true  if no record is found
			return 0, nil
		}
		return 0, err
	}

	return int(userChallenges.Tries), nil
}

func UpdateUserChallengeTries(userID uint, challengeID uint) error {
	DBMux.Lock()
	defer DBMux.Unlock()

	var userChallenges UserChallenges
	err := Db.Where("user_id = ? AND challenge_id = ?", userID, challengeID).First(&userChallenges).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			// Create a new record if not found
			userChallenges = UserChallenges{
				UserID:      userID,
				ChallengeID: challengeID,
				Tries:       1,
				Solved:      false,
			}
			return Db.Create(&userChallenges).Error
		}
		return err
	}

	updates := map[string]interface{}{
		"tries": userChallenges.Tries + 1,
	}

	tx := Db.Model(&UserChallenges{}).Where("user_id = ? AND challenge_id = ?", userID, challengeID).Updates(updates)

	return tx.Error
}

// Update an entry for the challenge in the Challenge table
func UpdateChallenge(chall *Challenge, m map[string]interface{}) error {

	DBMux.Lock()
	defer DBMux.Unlock()

	return Db.Omit(clause.Associations).Where("id = ?", chall.ID).Model(chall).Updates(m).Error
}

// This function updates a challenge entry in the database, whereMap is the map
// which contains key value pairs of column and values to filter out the record
// to update. chall is the Challenge variable with the values to update with.
// This function returns any error that might occur while updating the challenge
// entry which includes the error in case the challenge already does not exist in the
// database.
func BatchUpdateChallenge(whereMap map[string]interface{}, chall Challenge) error {
	var challenge Challenge

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Where(whereMap).First(&challenge)
	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return fmt.Errorf("no challenge entry to update : WhereClause : %s", whereMap)
	}

	if tx.Error != nil {
		return tx.Error
	}

	// Update the found entry
	tx = Db.Model(&challenge).Updates(chall)

	return tx.Error
}

// Get Related Tags
func GetRelatedTags(challenge *Challenge) ([]Tag, error) {
	var tags []Tag

	DBMux.Lock()
	defer DBMux.Unlock()

	if err := Db.Model(challenge).Association("Tags").Error; err != nil {
		return tags, err
	}

	return tags, nil
}

// Get Related Users
func GetRelatedUsers(challenge *Challenge) ([]User, error) {
	var users []User

	DBMux.Lock()
	defer DBMux.Unlock()

	// Query users who have solved this challenge by checking the user_challenges table
	if err := Db.Joins("JOIN user_challenges ON users.id = user_challenges.user_id").
		Where("user_challenges.challenge_id = ? AND user_challenges.solved = ?", challenge.ID, true).
		Find(&users).Error; err != nil {
		return users, err
	}

	return users, nil
}

// Function fetches total number of solves for a challenge and
// Did the user solve this challenge
func GetChallengeSolveInfo(challengeID uint, userID uint) (uint16, bool, error) {
	type result struct {
		TotalSolves int64
		UserSolved  bool
	}
	var res result

	DBMux.Lock()
	defer DBMux.Unlock()

	err := Db.Raw(`
		SELECT 
			COUNT(*) FILTER (WHERE uc.solved = true) AS total_solves,
			EXISTS (
				SELECT 1
				FROM user_challenges uc2
				JOIN users u2 ON u2.id = uc2.user_id
				WHERE uc2.challenge_id = ? AND uc2.user_id = ? AND uc2.solved = true AND u2.role = 'contestant'
			) AS user_solved
		FROM user_challenges uc
		JOIN users u ON u.id = uc.user_id
		WHERE uc.challenge_id = ? AND u.role = 'contestant'
	`, challengeID, userID, challengeID).Scan(&res).Error

	if err != nil {
		return 0, false, err
	}

	return uint16(res.TotalSolves), res.UserSolved, nil
}

func DeleteChallengeEntry(challenge *Challenge) error {
	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Begin()

	if tx.Error != nil {
		return fmt.Errorf("error while starting transaction : %s", tx.Error)
	}

	if err := tx.Unscoped().Delete(challenge).Error; err != nil {
		tx.Rollback()
		return err
	}

	return tx.Commit().Error
}

// Query challenges table to get all the entries in the table
func QueryAllSubmissions() ([]UserChallenges, error) {
	var userChallenges []UserChallenges

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Find(&userChallenges)

	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return nil, nil
	}

	return userChallenges, tx.Error
}

func QuerySubmissionsWithPagination(limit, offset int) ([]UserChallenges, error) {
	var userChallenges []UserChallenges

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Table("user_challenges").
		Select("user_challenges.*").
		Joins("JOIN users ON users.id = user_challenges.user_id").
		Where("users.role = ?", "contestant").
		Order("user_challenges.created_at DESC").
		Limit(limit).
		Offset(offset).
		Find(&userChallenges)

	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return nil, nil
	}

	return userChallenges, tx.Error
}

// QuerySubmissions queries all challenge where column matches
func QuerySubmissions(whereMap map[string]interface{}) ([]UserChallenges, error) {
	var userChallenges []UserChallenges

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Where(whereMap).Find(&userChallenges)
	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return nil, nil
	}

	if tx.Error != nil {
		return userChallenges, tx.Error
	}

	return userChallenges, nil
}

func SaveFlagSubmission(user_challenges *UserChallenges) error {
	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Begin()

	if tx.Error != nil {
		return fmt.Errorf("error while saving record: %s", tx.Error)
	}

	// Check if a row already exists for this user+challenge pair (created by UpdateUserChallengeTries)
	var existing UserChallenges
	err := tx.Where("user_id = ? AND challenge_id = ?", user_challenges.UserID, user_challenges.ChallengeID).First(&existing).Error
	if err == nil {
		// Row exists: update it to mark as solved with the current timestamp
		if updateErr := tx.Model(&existing).Updates(map[string]interface{}{
			"solved":     user_challenges.Solved,
			"created_at": user_challenges.CreatedAt,
		}).Error; updateErr != nil {
			tx.Rollback()
			return updateErr
		}
	} else if errors.Is(err, gorm.ErrRecordNotFound) {
		// No existing row: create a new one
		if createErr := tx.Create(user_challenges).Error; createErr != nil {
			tx.Rollback()
			return createErr
		}
	} else {
		tx.Rollback()
		return err
	}

	return tx.Commit().Error
}

// Create a new entry in the DynamicFlag table
func CreateDynamicFlagEntry(dynamicFlag *DynamicFlag) error {

	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Begin()

	if tx.Error != nil {
		return fmt.Errorf("error while starting transaction: %s", tx.Error)
	}

	if err := tx.FirstOrCreate(dynamicFlag, *dynamicFlag).Error; err != nil {
		tx.Rollback()
		return err
	}

	return tx.Commit().Error
}

// Query the entries in the DynamicFlag table
func QueryDynamicFlagEntries(whereMap map[string]interface{}) ([]DynamicFlag, error) {
	var dynamicFlags []DynamicFlag

	DBMux.Lock()
	defer DBMux.Unlock()

	whereMap = normalizeDynamicFlagWhereMap(whereMap)
	tx := Db.Where(whereMap).Find(&dynamicFlags)
	if errors.Is(tx.Error, gorm.ErrRecordNotFound) {
		return []DynamicFlag{}, nil
	}

	return dynamicFlags, tx.Error
}

func normalizeDynamicFlagWhereMap(whereMap map[string]interface{}) map[string]interface{} {
	normalized := make(map[string]interface{}, len(whereMap))
	for key, value := range whereMap {
		switch key {
		case "Name":
			normalized["name"] = value
		case "Flag":
			normalized["flag"] = value
		default:
			normalized[key] = value
		}
	}
	return normalized
}

func DeleteDynamicFlagsByChallengeName(name string) error {
	DBMux.Lock()
	defer DBMux.Unlock()

	return Db.Unscoped().Where("name = ?", name).Delete(&DynamicFlag{}).Error
}

func SubtractScoreFromSolvers(challengeID uint) error {
	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Begin()
	if tx.Error != nil {
		return fmt.Errorf("error while starting transaction: %v", tx.Error)
	}

	var challenge Challenge
	if err := tx.Where("id = ?", challengeID).First(&challenge).Error; err != nil {
		tx.Rollback()
		return fmt.Errorf("error fetching challenge: %v", err)
	}

	pointsToSubtract := challenge.Points

	var solvers []UserChallenges
	if err := tx.Where("challenge_id = ? AND solved = ?", challengeID, true).Find(&solvers).Error; err != nil {
		tx.Rollback()
		return fmt.Errorf("error fetching solvers: %v", err)
	}

	for _, solver := range solvers {
		if err := tx.Model(&User{}).Where("id = ?", solver.UserID).
			UpdateColumn("score", gorm.Expr("CASE WHEN score - ? < 0 THEN 0 ELSE score - ? END", pointsToSubtract, pointsToSubtract)).Error; err != nil {
			tx.Rollback()
			return fmt.Errorf("error updating score for user %d: %v", solver.UserID, err)
		}
	}

	return tx.Commit().Error
}

func DeleteAllUserChallenges(challengeID uint) error {
	DBMux.Lock()
	defer DBMux.Unlock()

	tx := Db.Begin()
	if tx.Error != nil {
		return fmt.Errorf("error while starting transaction: %v", tx.Error)
	}

	if err := tx.Where("challenge_id = ?", challengeID).Delete(&UserChallenges{}).Error; err != nil {
		tx.Rollback()
		return fmt.Errorf("error deleting user challenge entries: %v", err)
	}

	return tx.Commit().Error
}

// QueryChallAttempts queries all attempts for a given challenge ID
func QueryChallAttempts(chall_id uint64) ([]ChallengeAttempt, error) {
	var attempts []ChallengeAttempt

	DBMux.Lock()
	defer DBMux.Unlock()

	err := Db.Table("user_challenges").
		Select("user_challenges.id as id, user_challenges.user_id as user_id, users.username as username, user_challenges.created_at as solved_at, user_challenges.flag as flag, user_challenges.solved as correct, user_challenges.cheating as cheating").
		Joins("JOIN users ON users.id = user_challenges.user_id").
		Where("user_challenges.challenge_id = ?", chall_id).
		Order("user_challenges.created_at ASC").
		Scan(&attempts).Error

	if err != nil {
		return nil, err
	}

	return attempts, nil
}

// QueryUserAttempts queries all attempts for a given user ID
func QueryUserAttempts(user_id uint) ([]ChallengeAttempt, error) {
	var attempts []ChallengeAttempt

	DBMux.Lock()
	defer DBMux.Unlock()

	err := Db.Table("user_challenges").
		Select("user_challenges.id as id, user_challenges.user_id as user_id, user_challenges.challenge_id as challenge_id, user_challenges.created_at as solved_at, user_challenges.flag as flag, user_challenges.solved as correct, user_challenges.cheating as cheating").
		Where("user_challenges.user_id = ?", user_id).
		Order("user_challenges.created_at ASC").
		Scan(&attempts).Error

	if err != nil {
		return nil, err
	}

	return attempts, nil
}

// timeElapsed returns the aggregation bucket for the given duration
func timeElapsed() TimeAggBucket {
	startStr := config.Cfg.CompetitionInfo.StartingTime
	// The format is "16:31:23 UTC: +05:30, 03 February 2025, Monday"
	// We'll parse only the part up to the date, ignoring the weekday
	// e.g. "16:31:23 UTC: +05:30, 03 February 2025"
	parts := strings.Split(startStr, ",")
	if len(parts) < 2 {
		log.Errorf("invalid StartingTime format: %s", startStr)
		return Between1MonthAnd1Year
	}
	startTimePart := strings.TrimSpace(parts[0])
	startDatePart := strings.TrimSpace(parts[1])
	startParseStr := startTimePart + ", " + startDatePart
	start, err := dateparse.ParseLocal(startParseStr)
	if err != nil {
		log.Errorf("failed to parse StartingTime: %v", err)
		return Between1MonthAnd1Year
	}
	end := time.Now()
	diff := end.Sub(start)
	minutes := diff.Minutes()
	hours := diff.Hours()
	days := hours / 24
	months := days / 30

	switch {
	case minutes < 10:
		return LessThan10Min
	case minutes < 100:
		return Between10And100Min
	case hours < 12:
		return Between100MinAnd12Hr
	case hours < 24:
		return Between12HrAnd24Hr
	case days < 30:
		return Between1DayAnd1Month
	case months < 12:
		return Between1MonthAnd1Year
	default:
		return MoreThan1Year
	}
}

// aggregateTimeSeries aggregates the time series data based on the bucket
func aggregateTimeSeries(ts []TimeSeries, bucket TimeAggBucket) []TimeSeries {
	if len(ts) <= 10 {
		return ts
	}

	var interval time.Duration
	switch bucket {
	case LessThan10Min:
		return ts
	case Between10And100Min:
		interval = 10 * time.Minute
	case Between100MinAnd12Hr:
		interval = 1 * time.Hour
	case Between12HrAnd24Hr:
		interval = 2 * time.Hour
	case Between1DayAnd1Month:
		interval = 72 * time.Hour // 3 days
	case Between1MonthAnd1Year:
		interval = 30 * 24 * time.Hour // 1 month
	case MoreThan1Year:
		interval = 365 * 24 * time.Hour // 1 year
	default:
		return ts
	}

	var agg []TimeSeries
	var lastAdded time.Time
	for i, point := range ts {
		if i == 0 {
			agg = append(agg, point)
			lastAdded = point.Timestamp
			continue
		}
		if point.Timestamp.Sub(lastAdded) >= interval {
			agg = append(agg, point)
			lastAdded = point.Timestamp
		}
	}

	if len(agg) == 0 || !agg[len(agg)-1].Timestamp.Equal(ts[len(ts)-1].Timestamp) {
		agg = append(agg, ts[len(ts)-1])
	}
	return agg
}

/*
QueryTimeSeriesForTopUsers returns a slice of UserLeaderboardResp for the given list of user IDs,
containing each user's cumulative score time series data.

Time Buckets:
- The function uses time buckets to aggregate time series data for each user, reducing the number of data points for visualization.
- The time buckets are determined by the timeElapsed() function, which calculates the elapsed time since the competition started and selects a bucket:
  - LessThan10Min: No aggregation, all points shown.
  - Between10And100Min: 10-minute intervals.
  - Between100MinAnd12Hr: 1-hour intervals.
  - Between12HrAnd24Hr: 2-hour intervals.
  - Between1DayAnd1Month: 3-day intervals.
  - Between1MonthAnd1Year: 1-month intervals.
  - MoreThan1Year: 1-year intervals.

This approach ensures that the returned time series is concise and suitable for plotting, while still reflecting the user's progress over time.
*/
func QueryTimeSeriesForTopUsers(topUserId []uint) []UserLeaderboardResp {
	var results []UserLeaderboardResp

	if len(topUserId) == 0 {
		return results
	}

	DBMux.Lock()
	defer DBMux.Unlock()

	type userChallengeRow struct {
		UserID    uint
		Username  string
		CreatedAt time.Time
		Points    uint
		IsHint    bool
	}
	var allRows []userChallengeRow

	if err := Db.Table("user_challenges").
		Select("DISTINCT ON (user_challenges.user_id, user_challenges.challenge_id) user_challenges.user_id, users.username, user_challenges.created_at, challenges.points, false AS is_hint").
		Joins("JOIN challenges ON user_challenges.challenge_id = challenges.id").
		Joins("JOIN users ON user_challenges.user_id = users.id").
		Where("user_challenges.user_id IN ? AND user_challenges.solved = ?", topUserId, true).
		Order("user_challenges.user_id, user_challenges.challenge_id, user_challenges.created_at ASC").
		Scan(&allRows).Error; err != nil {
		return results
	}

	var hintRows []userChallengeRow
	if err := Db.Table("user_hints").
		Select("user_hints.user_id, users.username, COALESCE(user_hints.created_at, NOW()) AS created_at, hints.points, true AS is_hint").
		Joins("JOIN hints ON user_hints.hint_id = hints.hint_id").
		Joins("JOIN users ON user_hints.user_id = users.id").
		Where("user_hints.user_id IN ?", topUserId).
		Scan(&hintRows).Error; err != nil {
		return results
	}

	allRows = append(allRows, hintRows...)

	// Re-sort by user_id then created_at for proper cumulative score calculation
	sort.Slice(allRows, func(i, j int) bool {
		if allRows[i].UserID != allRows[j].UserID {
			return allRows[i].UserID < allRows[j].UserID
		}
		return allRows[i].CreatedAt.Before(allRows[j].CreatedAt)
	})

	userRows := make(map[uint][]userChallengeRow)
	userMap := make(map[uint]string)
	for _, row := range allRows {
		userRows[row.UserID] = append(userRows[row.UserID], row)
		userMap[row.UserID] = row.Username
	}

	for _, userId := range topUserId {
		rows := userRows[userId]
		username, ok := userMap[userId]
		if !ok {
			continue
		}

		var timeSeriesRaw []TimeSeries
		var cumulativeScore uint = 0
		for _, r := range rows {
			if r.IsHint {
				if cumulativeScore < r.Points {
					cumulativeScore = 0
				} else {
					cumulativeScore -= r.Points
				}
			} else {
				cumulativeScore += r.Points
			}

			timeSeriesRaw = append(timeSeriesRaw, TimeSeries{
				Timestamp: r.CreatedAt,
				Score:     cumulativeScore,
			})
		}

		var timeSeries []TimeSeries
		if len(timeSeriesRaw) <= 10 {
			timeSeries = timeSeriesRaw
		} else if len(timeSeriesRaw) > 0 {
			bucket := timeElapsed()
			timeSeries = aggregateTimeSeries(timeSeriesRaw, bucket)
		}

		var rank int64 = 0

		results = append(results, UserLeaderboardResp{
			Id:             userId,
			Username:       username,
			Score:          uint(cumulativeScore),
			Rank:           rank,
			TimeSeriesdata: timeSeries,
		})
	}

	return results
}
