[author]
name = "contact"
email = "contact@sdslabs.co.in"

[challenge.metadata]
name = "xinetd-service"
flag = "CTF{not_the_flag}"
type = "service"
points = 500
maxAttemptLimit = 10
preReqs = ["simple", "web-php"]

[[challenge.metadata.hints]]
text = "simple_hint_1"
points = 10

[[challenge.metadata.hints]]
text = "simple_hint_2"
points = 20


[challenge.env]
apt_deps = ["gcc", "socat"]
setup_scripts = ["setup.sh"]
xinetd_conf = "ctf.xinetd"
service_path = "pwn"
ports = [10003]
default_port = 10003

[resource]
cpu_shares = 512
memory_limit = 536870912
pids_limit = 100
cpuslimit = 0.25
