[author]
name = "contact"
email = "contact@sdslabs.co.in"
ssh_key = "ssh-rsa AAAAB3NzaC1y"

[challenge.metadata]
name = "xinetd-service"
flag = "CTF{not_the_flag}"
type = "service"
points = 500
max_attempt_limit=10

[[challenge.metadata.hints]]
text = "simple_hint_1"
points = 10

[[challenge.metadata.hints]]
text = "simple_hint_2"
points = 20

preReqs = ["simple", "web-php"]



[challenge.env]
apt_deps = ["gcc", "socat"]
setup_scripts = ["setup.sh"]
xinetd_config = "ctf.xinetd"
service_path = "pwn"
ports = [10003]
