[author]
name = "fristonio"
email = "contact+fristonio@sdslabs.co.in"
ssh_key = "ssh-rsa AAAAB3NzaC1y"

[challenge.metadata]
name = "web-php"
flag = "BACKDOOR{SAMPLE_WEB_FLAG}"
type = "web:php:7.1:cli"
hints = ["web_hint_1", "web_hint_2"]
failSolveLimit = 3

[challenge.env]
ports = [10002]
web_root = "challenge"
default_port = 10002
