# $ ~/.beast 
# ❮❮ tree
# .
# ├── auth_file
# ├── beast.db
# ├── config.toml
# └── .static.beast.htpasswd
# ├── remote/
# │   └── hack-test
# ├── secrets/
# │   ├── key.priv
# │   └── key.pub
# └── staging/
#
# Sample snapshot of .beast directory.
# Make sure the hack-test is a valid git directory
# Make sure you provide a valid existing authorized_keys_file
# Make sure key.pub is added to the deployed keys of the beast remote repo

# scripts_dir = "/home/vsts/.beast/scripts"
# slack_webhook = ""
available_sidecars = ["mysql"]
jwt_secret = "beast"
allowed_base_images = ["ubuntu:16.04", "php:7.1-cli"]
authorized_keys_file = "/home/vsts/.beast/authorized_keys"

[[remote]]
ssh_key = "/home/vsts/.beast/secret.key"
url = "git@github.com:sdslabs/nonexistent.git"
name = "nonexistent"
branch = "nonexistent"

[[notification_webhooks]]
url = ""
service_name = "discord"
active = true

[[notification_webhooks]]
url = ""
service_name = "slack"
active = false
